# Generated by Django 3.1.3 on 2021-04-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0003_auto_20210401_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(default='user-icon.PNG', upload_to=''),
        ),
    ]
