# Generated by Django 3.1.3 on 2021-04-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0004_auto_20210401_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(default='img/user-icon.png', upload_to=''),
        ),
    ]
