# Generated by Django 3.1.3 on 2021-04-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0008_auto_20210403_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
