# Generated by Django 3.1.3 on 2021-04-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0009_voter_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='value',
            field=models.BooleanField(default=False),
        ),
    ]
