# Generated by Django 3.1.3 on 2021-04-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0010_auto_20210403_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='value',
            new_name='vote_down',
        ),
        migrations.AddField(
            model_name='voter',
            name='vote_up',
            field=models.BooleanField(default=False),
        ),
    ]
