# Generated by Django 3.1.3 on 2021-04-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0012_auto_20210404_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='viwes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
