# Generated by Django 3.1.3 on 2021-04-15 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0013_post_viwes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='viwes',
            new_name='views',
        ),
        migrations.DeleteModel(
            name='PostViews',
        ),
    ]
